### ISSUE TITLE
Can we have Docker Container?

### ISSUE THREAD

**Issue by hardik-a-joshi** [dkackman/fing#18]
Works well, but having a docker container can reduce a lot of time.

**Comment by hardik-a-joshi** [comment]
docker run giving error

`File not found error: No such file or directory: '/fing/models/CompVis.stable-diffuion-v1-4.compose.pipeline''`

**Comment by dkackman** [comment]
So I've been working on this but I'm finding it doesn't really add much value.

1) even without the model files the resulting image is quite large (>10GB even after using miniconda) and won't upload to docker hub. 
2) You still need to get the model files in there. I can't/won't include them in a shared image as that would be violating their terms  as it would bypass the license agreement. So you still need download the models and serialize them and share a volume with the image (I am not yet able to get the images to download as part of the image build)

I can try to get the model serialization to happen as part of the build but you'd have to run it and provide your huggingface token. If you think that'd be useful I can see if I can get that to work, but I don't see this turning into an image that could be pulled form somewhere and used immediately.

**Comment by dkackman** [comment]
I got it so that the models and pipelines get downloaded and cached during the image build. You need to provide your hugginface token during the image build

```
docker build -t dkackman/fing --build-arg HUGGINGFACE_TOKEN=<YOUR TOKEN> .
docker run --gpus all --env HUGGINGFACE_TOKEN=<YOUR TOKEN> dkackman/fing
```

You might need to install the [nvidia container toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) on you host machine for the build to work.

It's gonna take awhile. Let me know if it works.

**Comment by hardik-a-joshi** [comment]
Okay, let me give it a try

**Comment by dkackman** [comment]
did you ever have any luck?

**Comment by adhikjoshi** [comment]
Did made docker image, worked fine. But issue is that there is no concurrency.

Adding celery tasks to manage it in background and send response.

**Comment by dkackman** [comment]
It should use your gpus in a round robin and allow more than 1 to process a job at a time. Or are you meaning queuing? As in it rejects requests when it's busy? That is by design as I think it is better managed upstream as your doing. That being said, if you replace `device_pool.py` with this, it will queue requests when all gpu's are busy.:

```python
from typing import List
from .device import Device
from threading import Lock
import asyncio

mutex: Lock = Lock()

available: List[Device] = []

def add_device_to_pool(device: Device):
    mutex.acquire(True, 2)
    try:
        available.append(device)
    finally:
        mutex.release()


def _remove_device_from_pool():
    mutex.acquire(True, 2)
    try:
        if len(available) > 0:
            return available.pop(0)

        return None
    finally:
        mutex.release()


async def remove_device_from_pool():
    device = _remove_device_from_pool()
    while device is None:
        await asyncio.sleep(5)
        device = _remove_device_from_pool()

    return device
```

**Comment by adhikjoshi** [comment]
Yes, i did something like this before, but if puts request to wait, and if there are 10-20 requests, connection will be closed. 

but if we can return "task_id" in API, which we can query for response. it can remove wait time on API.

it is something i am trying to implement using celery.

Also,

I made docker image for runpod. works well.

https://github.com/adhikjoshi/fing/pkgs/container/fing

**Comment by adhikjoshi** [comment]
on generator.py

```
except Exception as e:
    if len(e.args) > 0:
        if e.args[0] == "busy":
            raise HTTPException(423)
        if e.args[0] == "NSFW":
            raise HTTPException(406)  # Not Acceptable

    print(e)
    raise HTTPException(500)
```
Instead of sending busy exception, we can add task, and send task_id in response, which can be retrieved back.

**Comment by dkackman** [comment]
> Yes, i did something like this before, but if puts request to wait, and if there are 10-20 requests, connection will be closed.
> 
> but if we can return "task_id" in API, which we can query for response. it can remove wait time on API.
> 
> it is something i am trying to implement using celery.
> 
> Also,
> 
> I made docker image for runpod. works well.
> 
> https://github.com/adhikjoshi/fing/pkgs/container/fing

That's awesome. I could not get it to publish on the docker hub repo. Too large.
